default:
    # valid_key: "your_valid_key"
    # valid_rules: "your_valid_rules"
    # ckan_key: "your_ckan_key"
    # ckan_url: "your_ckan_url"
    # ckan_package: "your_ckan_package"
    # ckan_url_to_send: "your_ckan_url_to_send"
    portal_name: "One4All"
    portal_funder_name: !expr shiny::tags$a(href = "https://possibilitylab.berkeley.edu/", "pb Possibility Lab")
    portal_funder_link: "https://pbs.twimg.com/profile_images/1540022027288924160/bn2627cY_400x400.jpg"
    # s3_username: "your_s3_username"
    # s3_key_id: "your_s3_key_id"
    # s3_secret_key: "your_s3_secret_key"
    # s3_console_link: "your_s3_console_link"
    # s3_region: "your_s3_region"
    # s3_bucket: "your_s3_bucket"
    # mongo_key: "your_mongo_key"
    # mongo_collection: "your_mongo_collection"
    # apiKey: "your_mongo_apikey"
    rules_to_use: "www/microplastic_images/One4AllValidator_rules.csv"
    rules_example: "www/microplastic_images/One4AllValidator_rules.csv"
    valid_data_example: "www/microplastic_images/valid_example.xlsx"
    invalid_data_example: "www/microplastic_images/invalid_example.xlsx"
    twitter: "https://twitter.com/Win_OpenData"
    github:  "https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/tree/main/code/validator"
    license: "https://creativecommons.org/licenses/by/4.0/"
    contact: "win@mooreplasticresearch.org"
    dev: TRUE
    tutorial: "https://www.youtube.com/embed/LMpf5-K_tYQ"
    overview: "https://www.youtube.com/embed/GKsoNega7CY"
    contributors:
        p1: !expr bs4Dash::boxProfile(image = "https://i0.wp.com/mooreplasticresearch.org/wp-content/uploads/2022/03/20220321_104726_2.jpg?resize=1200%2C1600&ssl=1", title = "Win Cowger", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p2: !expr bs4Dash::boxProfile(image = "https://i0.wp.com/mooreplasticresearch.org/wp-content/uploads/2022/03/20220307_110138-1.jpg?resize=1188%2C1536&ssl=1", title = "Shelly Moore", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p3: !expr bs4Dash::boxProfile(image = "https://envisci.ucr.edu/sites/default/files/styles/profile_card_118_x_118/public/Hannah%20Hapich.jpg?h=cbdac610&itok=fjGpJ7uI", title = "Hannah Hapich", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p4: !expr bs4Dash::boxProfile(image = "https://scholar.googleusercontent.com/citations?view_op=view_photo&user=RS6imBYAAAAJ&citpid=2", title = "Scott Coffin", subtitle = "State Water Resources Control Board", bordered = FALSE)
        p5: !expr bs4Dash::boxProfile(image = "https://www.sfei.org/sites/default/files/styles/image_responsive/public/pictures/picture-32-1442945160.jpg?itok=mvmG2ydF", title = "Tony Hale", subtitle = "San Francisco Estuary Institute", bordered = FALSE)
        p6: !expr bs4Dash::boxProfile(image = "https://www.sfei.org/sites/default/files/styles/image_responsive/public/pictures/picture-553-1487880891.jpg?itok=Cj8_Csm5", title = "Diana Lin", subtitle = "San Francisco Estuary Institute", bordered = FALSE)
        p7: !expr bs4Dash::boxProfile(image = "https://www.sfei.org/sites/default/files/styles/image_responsive/public/pictures/picture-119-1436289327.jpg?itok=y2mzKV24", title = "Rebecca Sutton", subtitle = "San Francisco Estuary Institute", bordered = FALSE)
        p8: !expr bs4Dash::boxProfile(image = "", title = "Gabriel Daiess", subtitle = NULL, bordered = FALSE)
        p9: !expr bs4Dash::boxProfile(image = "https://www.sccwrp.org/wp/wp-content/uploads/2020/03/Leah-Thomas-Hampton-SCCWRP-bkg-WebAR.jpg", title = "Leah Thornton Hampton", subtitle = "Southern California Coastal Water Research Project", bordered = FALSE)
        p10: !expr bs4Dash::boxProfile(image = "", title = "Richard Nelson", subtitle = "California State Water Resources Control Board", bordered = FALSE)
        p11: !expr bs4Dash::boxProfile(image = "", title = "Haig Jack Minasian", subtitle = "CSU Long Beach", bordered = FALSE)
        p12: !expr bs4Dash::boxProfile(image = "", title = "Holden Ford", subtitle = "CSU Long Beach", bordered = FALSE)
        p13: !expr bs4Dash::boxProfile(image = "", title = "Anja Oca", subtitle = "CSU Long Beach", bordered = FALSE)
        p14: !expr bs4Dash::boxProfile(image = "https://photos.smugmug.com/photos/i-V6hDWm7/0/c09dd854/X2/i-V6hDWm7-X2.jpg", title = "Libby Heeren", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p15: !expr bs4Dash::boxProfile(image = "https://i0.wp.com/mooreplasticresearch.org/wp-content/uploads/2023/08/hannah.jpeg?w=1440&ssl=1", title = "Hannah Sherrod", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p16: !expr bs4Dash::boxProfile(image = "https://i0.wp.com/mooreplasticresearch.org/wp-content/uploads/2023/08/image_6483441.jpg?resize=1536%2C2048&ssl=1", title = "Nick Leong", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p17: !expr bs4Dash::boxProfile(image = "", title = "Fabian Gomez", subtitle = "Moore Institute for Plastic Pollution Research", bordered = FALSE)
        p18: !expr bs4Dash::boxProfile(image = "https://www.sfei.org/sites/default/files/styles/image_responsive-copy/public/pictures/picture-46-1435360424.jpg?itok=YbQWaQo2", title = "Gemma Shusterman", subtitle = "San Francisco Estuary Institute", bordered = FALSE)
        p19: !expr bs4Dash::boxProfile(image = "https://www.sfei.org/sites/default/files/styles/image_responsive-copy/public/pictures/picture-42-1429141783.jpg?itok=9aFT2lOu", title = "Adam Wong", subtitle = "San Francisco Estuary Institute", bordered = FALSE)
